# Generated by Django 5.2.17 on 2026-08-25 22:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrescriptionScan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_image', models.ImageField(blank=True, null=True, upload_to='prescriptions/')),
                ('raw_text', models.TextField(blank=True, help_text='Raw text extracted by OCR')),
                ('detected_medicines', models.JSONField(blank=True, default=list, help_text='Parsed list of drug names')),
                ('llm_analysis', models.TextField(blank=True, help_text='Clinical recommendations from LLM')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescription_scans', to='accounts.patientprofile')),
            ],
        ),
    ]
