# Generated by Django 5.2.17 on 2026-09-18 04:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('specialty', models.CharField(max_length=100)),
                ('department', models.CharField(choices=[('Neurology', 'Neurology'), ('Cardiology', 'Cardiology'), ('Geriatrics', 'Geriatrics'), ('Gastroenterology', 'Gastroenterology'), ('Orthopedics', 'Orthopedics'), ('Radiology', 'Radiology'), ('General Medicine', 'General Medicine')], default='Neurology', max_length=100)),
                ('qualification', models.CharField(max_length=150)),
                ('experience_years', models.PositiveIntegerField(default=10)),
                ('rating', models.FloatField(default=4.9)),
                ('avatar_url', models.CharField(default='https://images.unsplash.com/photo-1622253692010-333f2da6031d?w=300&h=300&fit=crop&crop=face', max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, default='+1 (800) 456-7890', max_length=30)),
                ('bio', models.TextField(blank=True)),
                ('available_days', models.CharField(default='Mon, Tue, Wed, Thu, Fri', max_length=100)),
                ('available_hours', models.CharField(default='09:00 AM - 05:00 PM', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_date', models.DateField()),
                ('time_slot', models.CharField(max_length=50)),
                ('reason', models.TextField(blank=True, help_text='Reason for consultation / symptoms')),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Confirmed', 'Confirmed'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Confirmed', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='accounts.patientprofile')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='appointments.doctor')),
            ],
        ),
    ]
