# Generated by Django 5.2.17 on 2026-08-25 22:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VRTestRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_taken', models.FloatField(help_text='Time taken in seconds')),
                ('errors', models.IntegerField(help_text='Navigation errors or incorrect recalls')),
                ('score', models.FloatField(help_text='Overall score out of 100')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vr_records', to='accounts.patientprofile')),
            ],
        ),
    ]
