# Generated by Django 5.2.17 on 2026-08-25 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TrainedModelArtifact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('model_type', models.CharField(max_length=50)),
                ('hyperparameters', models.JSONField(help_text='Selected hyperparameters')),
                ('metrics', models.JSONField(help_text='Accuracy, loss, validation metrics')),
                ('is_active', models.BooleanField(default=False, help_text='Set as current active prediction model')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
